version: '3.8'

services:
  api_service:
    build: ./api_service/
    volumes:
      - ./api_service/app:/app/app
    ports:
      - 5003:8000
    depends_on:
      - api_db
    env_file:
      - config.env
      - api_db_config.env    
  
  api_db:
    image: postgres
    ports:  # for debug purpuses
      - 5005:5432
    volumes:
      - ./api_db/postgres_data:/var/lib/postgresql/data/
    env_file:
      - api_db_config.env    
 