version: '3.8'

services:
  api_service:
    build: ./api_service/
    volumes:
      - ./api_service/app:/app/app
    ports:
      - 5003:8000
    depends_on:
      - db
    env_file:
      - config.env
  
  db:
    image: postgres
    ports:  # for debug purpuses
      - 5005:5432
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data/
    env_file:
      - config.env
  
  pgadmin:
    build: pgadmin
    env_file:
      - config.env
    ports:
      - "5050:80"
    links:
      - "db:pgsql-server"
 